#!/usr/bin/env bash
# 01-base-packages.sh — official repo packages (idempotent).
set -Eeuo pipefail

PKGS_CORE=(
    base-devel git curl wget unzip rsync man-db man-pages
    # Networking: iwd owns wifi (standalone — NOT via NetworkManager, which
    # fought iwd on this box). Wired DHCP + routes are handled by
    # systemd-networkd (part of systemd, no package). DNS is left to a static
    # /etc/resolv.conf, so resolved is intentionally NOT enabled. 07-services.sh
    # writes the iwd / networkd / polkit config and enables the services.
    iwd openssh
    pipewire pipewire-pulse pipewire-alsa wireplumber pavucontrol
    bluez bluez-utils blueman
    polkit polkit-gnome xdg-user-dirs xdg-utils
    qt5-wayland qt6-wayland
    wl-clipboard cliphist
    brightnessctl playerctl
    fastfetch htop btop fzf ripgrep fd bat eza zoxide jq
    # neovim — primary editor. The config (dotfiles/nvim) bootstraps lazy.nvim
    # and mason itself, so no plugin/LSP packages belong here; Telescope and
    # Treesitter reuse ripgrep/fd above plus base-devel's compiler.
    neovim
    alacritty
    # Interactive shell: zsh + fish-style autocomplete. zsh-autosuggestions
    # draws the grey inline suggestion from history; zsh-syntax-highlighting
    # colours the command line as you type; zsh-completions adds extra compdef
    # functions on top of zsh's built-in completion. All four are in the
    # official repos (no AUR). chsh to zsh is done in install.sh; the rc lives
    # at dotfiles/zsh/.zshrc and is linked by 08-link-dotfiles.sh.
    zsh zsh-completions zsh-autosuggestions zsh-syntax-highlighting
    ttf-jetbrains-mono-nerd ttf-firacode-nerd noto-fonts noto-fonts-emoji
    noto-fonts-cjk papirus-icon-theme adw-gtk-theme
    python python-pip python-gobject
    gtk3 gtk4 libadwaita
    cava
    mako
    swaybg
    # hyprlock — lock screen (replaced gtklock). Runs PARALLEL auth, so the
    # fingerprint reader and the password field are both live at once; gtklock's
    # single blocking PAM conversation could only do them in sequence. Standalone
    # ext-session-lock surface (no Hyprland); niri Mod+L spawns it. Its config is
    # GENERATED by rice-theme from templates/hyprlock.conf.tmpl. Manual-only lock.
    hyprlock
    # fprintd — fingerprint auth. hyprlock talks to it directly (parallel with
    # the password); sudo uses it via pam_fprintd in /etc/pam.d/sudo. Enrolment
    # is interactive — run `fprintd-enroll` once after install. Harmless where
    # there's no reader (verify just falls through to the password).
    fprintd
    # Quickshell — QtQuick-based shell; drives the Caelestia-style top bar.
    quickshell
    # Side-bar dock apps that live in the official repos. spotify is AUR (see
    # 03-aur-packages.sh); WhatsApp runs as a Chromium web app (see
    # scripts/whatsapp-web.sh); steam needs the multilib repo enabled, so it is
    # intentionally left out of the installer.
    chromium discord
    seatd
    # Login manager.
    ly
    # GPU stack — required for Niri to find a working EGL renderer.
    # In a VMware/QEMU VM you ALSO need to enable 3D acceleration in the
    # hypervisor settings; the packages alone aren't enough.
    # mesa-demos provides BOTH glxinfo and eglinfo on Arch (the package
    # names mesa-utils / egl-utils are Debian, not Arch).
    mesa mesa-demos vulkan-icd-loader vulkan-swrast
    xorg-xwayland
    # ImageMagick — wallpaper-init / wallpaper-next pre-blur the current
    # wallpaper into ~/.cache/lockscreen-bg.jpg so hyprlock has a fresh
    # background. Without it the lock surface falls back to whatever was
    # last cached.
    imagemagick
)

# Detect VM hypervisor and pull in guest tools for clipboard/resolution/3D.
case "$(systemd-detect-virt 2>/dev/null)" in
    vmware) PKGS_CORE+=( open-vm-tools gtkmm3 ) ;;
    kvm|qemu) PKGS_CORE+=( qemu-guest-agent spice-vdagent ) ;;
    oracle) PKGS_CORE+=( virtualbox-guest-utils ) ;;
esac

# Conditional: GPU/CPU microcode only matters bare-metal (personal + laptop).
PKGS_BAREMETAL=(
    intel-ucode amd-ucode
)

log "Refreshing pacman databases"
sudo pacman -Syu --noconfirm --needed

log "Installing core packages"
sudo pacman -S --needed --noconfirm "${PKGS_CORE[@]}"

if [[ "$PROFILE" != "vm" ]]; then
    log "Installing microcode (bare-metal profile: $PROFILE)"
    sudo pacman -S --needed --noconfirm "${PKGS_BAREMETAL[@]}" || true
fi

ok "base packages installed"
