#!/usr/bin/env bash
# 08-link-dotfiles.sh — symlink dotfiles into ~/.config (idempotent).
set -Eeuo pipefail

link() {
    local src="$1" dst="$2"
    mkdir -p "$(dirname "$dst")"
    if [[ -L "$dst" || -e "$dst" ]]; then
        if [[ -L "$dst" && "$(readlink -f "$dst")" == "$(readlink -f "$src")" ]]; then
            return 0
        fi
        local bak="${dst}.bak.$(date +%s)"
        warn "backing up existing $dst → $bak"
        mv "$dst" "$bak"
    fi
    ln -s "$src" "$dst"
    ok "linked $dst"
}

# Niri compositor. config.kdl is GENERATED (base + active profile fragment) by
# `rice-profile`, NOT symlinked — niri's layout{}/animations{} are single nodes,
# so the full/light variants can't be layered via include and are concatenated
# instead. Link the three source fragments; config.kdl itself is built below,
# after the scripts (rice-profile) are installed.
link "$DOTFILES_DIR/niri/config.base.kdl"       "$HOME/.config/niri/config.base.kdl"
link "$DOTFILES_DIR/niri/config.full.kdl"       "$HOME/.config/niri/config.full.kdl"
link "$DOTFILES_DIR/niri/config.light.kdl"      "$HOME/.config/niri/config.light.kdl"
# A stale config.kdl symlink from a previous install would shadow the generated
# file; replace it with a real generated file.
if [[ -L "$HOME/.config/niri/config.kdl" ]]; then
    warn "removing old config.kdl symlink (now generated by rice-profile)"
    rm -f "$HOME/.config/niri/config.kdl"
fi

# config.kdl does `include "monitor.kdl"` unconditionally. That file is written
# by nwg-displays when the user arranges screens visually, so on a fresh install
# it does not exist yet — and niri's `include` is NOT optional, so the missing
# file makes `niri validate` (below) AND every later session launch fail with
# "failed to read included config". Seed an empty placeholder so the include
# resolves; the hardcoded output{} blocks in config.kdl drive the initial
# layout until nwg-displays overwrites this. niri resolves the include relative
# to the symlink's directory (~/.config/niri), not the repo, so this stays out
# of version control.
if [[ ! -e "$HOME/.config/niri/monitor.kdl" ]]; then
    cat > "$HOME/.config/niri/monitor.kdl" <<'EOF'
// Monitor layout generated by nwg-displays — empty until you arrange screens.
// Run `nwg-displays` to populate this; the output{} blocks in config.kdl
// provide the initial layout in the meantime.
EOF
    ok "seeded placeholder niri/monitor.kdl"
fi

# Bars, launcher overlay, and power flyout are all Quickshell-driven.
link "$DOTFILES_DIR/quickshell"                 "$HOME/.config/quickshell"

# Terminal, notifications, audio visualizer, system utilities.
link "$DOTFILES_DIR/alacritty/alacritty.toml"   "$HOME/.config/alacritty/alacritty.toml"
# Interactive shell rc. Unlike the others this lives at ~/.zshrc, not under
# ~/.config — zsh reads $ZDOTDIR/.zshrc and $ZDOTDIR defaults to $HOME. The
# fish-style autocomplete (autosuggestions + syntax highlighting + completion)
# is wired up here; packages come from 01-base-packages.sh and the login shell
# is switched to zsh in install.sh.
link "$DOTFILES_DIR/zsh/.zshrc"                 "$HOME/.zshrc"
link "$DOTFILES_DIR/gtk-3.0/settings.ini"       "$HOME/.config/gtk-3.0/settings.ini"
link "$DOTFILES_DIR/gtk-4.0/settings.ini"       "$HOME/.config/gtk-4.0/settings.ini"
link "$DOTFILES_DIR/mako/config"                "$HOME/.config/mako/config"
link "$DOTFILES_DIR/cava/config"                "$HOME/.config/cava/config"
link "$DOTFILES_DIR/fastfetch/config.jsonc"     "$HOME/.config/fastfetch/config.jsonc"
link "$DOTFILES_DIR/btop/btop.conf"              "$HOME/.config/btop/btop.conf"
link "$DOTFILES_DIR/btop/themes/driftos.theme"   "$HOME/.config/btop/themes/driftos.theme"

# gtklock — lock screen (replaces Quickshell's unstable WlSessionLock).
link "$DOTFILES_DIR/gtklock"                     "$HOME/.config/gtklock"

# Scripts → both ~/.local/bin (interactive shell) AND /usr/local/bin (every
# PAM/systemd session). niri's spawn-at-startup uses bare names like
# `wallpaper-init` and `power-menu`; those resolve via the session PATH which
# login(1) bootstraps from /etc/profile, and that path does NOT
# include ~/.local/bin on Arch. Installing to /usr/local/bin (which IS in
# the default PATH) means niri can always find them.
mkdir -p "$HOME/.local/bin"
for s in "$SCRIPTS_DIR"/*.sh; do
    name="$(basename "$s")"
    install -m755 "$s" "$HOME/.local/bin/${name%.sh}"
    sudo install -m755 "$s" "/usr/local/bin/${name%.sh}"
    ok "installed script: ${name%.sh}"
done

# Generate the initial niri config.kdl now that rice-profile is on PATH. Seed
# from the kernel cmdline (rice.profile=) if present, else honour any saved
# choice, else default to full. rice-profile validates before writing, so a
# broken fragment fails here loudly rather than at first login.
log "Generating niri config.kdl via rice-profile"
"$HOME/.local/bin/rice-profile-seed" || {
    warn "rice-profile-seed failed; falling back to explicit full profile"
    "$HOME/.local/bin/rice-profile" full
}
ok "niri config.kdl generated (profile: $("$HOME/.local/bin/rice-profile" status))"

# Fail loudly if the linked niri config doesn't parse on the installed niri
# version. Without this, parse errors only surface when the user logs in via
# greetd, which then bounces them straight back to the greeter — a confusing
# loop to debug from a cold install.
if command -v niri >/dev/null 2>&1; then
    log "Validating niri config against installed niri"
    # `niri validate` (no args) reads the user's default config location, i.e.
    # the config.kdl we just generated at ~/.config/niri/config.kdl. (rice-profile
    # already validated the temp file before swapping it in; this is a belt-and-
    # suspenders check against the installed niri.) Long-form --config is
    # supported on all niri versions; -c is not.
    if ! niri validate >/tmp/niri-validate.log 2>&1; then
        warn "niri config failed to validate:"
        sed 's/^/    /' /tmp/niri-validate.log
        warn "Fix dotfiles/niri/config.base.kdl or config.{full,light}.kdl and re-run install.sh."
        exit 1
    fi
    ok "niri config validates"
fi

ok "dotfiles linked"
