#!/usr/bin/env bash
# 08-link-dotfiles.sh — symlink dotfiles into ~/.config (idempotent).
set -Eeuo pipefail

link() {
    local src="$1" dst="$2"
    mkdir -p "$(dirname "$dst")"
    if [[ -L "$dst" || -e "$dst" ]]; then
        if [[ -L "$dst" && "$(readlink -f "$dst")" == "$(readlink -f "$src")" ]]; then
            return 0
        fi
        local bak="${dst}.bak.$(date +%s)"
        warn "backing up existing $dst → $bak"
        mv "$dst" "$bak"
    fi
    ln -s "$src" "$dst"
    ok "linked $dst"
}

# Niri compositor
link "$DOTFILES_DIR/niri/config.kdl"            "$HOME/.config/niri/config.kdl"

# config.kdl does `include "monitor.kdl"` unconditionally. That file is written
# by nwg-displays when the user arranges screens visually, so on a fresh install
# it does not exist yet — and niri's `include` is NOT optional, so the missing
# file makes `niri validate` (below) AND every later session launch fail with
# "failed to read included config". Seed an empty placeholder so the include
# resolves; the hardcoded output{} blocks in config.kdl drive the initial
# layout until nwg-displays overwrites this. niri resolves the include relative
# to the symlink's directory (~/.config/niri), not the repo, so this stays out
# of version control.
if [[ ! -e "$HOME/.config/niri/monitor.kdl" ]]; then
    cat > "$HOME/.config/niri/monitor.kdl" <<'EOF'
// Monitor layout generated by nwg-displays — empty until you arrange screens.
// Run `nwg-displays` to populate this; the output{} blocks in config.kdl
// provide the initial layout in the meantime.
EOF
    ok "seeded placeholder niri/monitor.kdl"
fi

# Both bars (top-bar dashboard + left side-bar) are Quickshell-driven.
link "$DOTFILES_DIR/quickshell"                 "$HOME/.config/quickshell"

# App launcher — rofi with Spotlight-style theme
link "$DOTFILES_DIR/rofi"                        "$HOME/.config/rofi"

# Side terminal, launcher, notifications, audio visualizer
link "$DOTFILES_DIR/alacritty/alacritty.toml"   "$HOME/.config/alacritty/alacritty.toml"
link "$DOTFILES_DIR/gtk-3.0/settings.ini"       "$HOME/.config/gtk-3.0/settings.ini"
link "$DOTFILES_DIR/gtk-4.0/settings.ini"       "$HOME/.config/gtk-4.0/settings.ini"
link "$DOTFILES_DIR/fuzzel/fuzzel.ini"          "$HOME/.config/fuzzel/fuzzel.ini"
link "$DOTFILES_DIR/mako/config"                "$HOME/.config/mako/config"
link "$DOTFILES_DIR/cava/config"                "$HOME/.config/cava/config"
link "$DOTFILES_DIR/fastfetch/config.jsonc"     "$HOME/.config/fastfetch/config.jsonc"
link "$DOTFILES_DIR/btop/btop.conf"              "$HOME/.config/btop/btop.conf"
link "$DOTFILES_DIR/btop/themes/driftos.theme"   "$HOME/.config/btop/themes/driftos.theme"
link "$DOTFILES_DIR/swaylock/config"            "$HOME/.config/swaylock/config"

# gtklock — lock screen (replaces Quickshell's unstable WlSessionLock).
link "$DOTFILES_DIR/gtklock"                     "$HOME/.config/gtklock"

# Scripts → both ~/.local/bin (interactive shell) AND /usr/local/bin (every
# PAM/systemd session). niri's spawn-at-startup uses bare names like
# `wallpaper-init` and `power-menu`; those resolve via the session PATH which
# login(1) bootstraps from /etc/profile, and that path does NOT
# include ~/.local/bin on Arch. Installing to /usr/local/bin (which IS in
# the default PATH) means niri can always find them.
mkdir -p "$HOME/.local/bin"
for s in "$SCRIPTS_DIR"/*.sh; do
    name="$(basename "$s")"
    install -m755 "$s" "$HOME/.local/bin/${name%.sh}"
    sudo install -m755 "$s" "/usr/local/bin/${name%.sh}"
    ok "installed script: ${name%.sh}"
done

# Fail loudly if the linked niri config doesn't parse on the installed niri
# version. Without this, parse errors only surface when the user logs in via
# greetd, which then bounces them straight back to the greeter — a confusing
# loop to debug from a cold install.
if command -v niri >/dev/null 2>&1; then
    log "Validating niri config against installed niri"
    # `niri validate` (no args) reads the user's default config location, which
    # is the symlink we just placed at ~/.config/niri/config.kdl. Long-form
    # --config is supported on all niri versions; -c is not.
    if ! niri validate >/tmp/niri-validate.log 2>&1; then
        warn "niri config failed to validate:"
        sed 's/^/    /' /tmp/niri-validate.log
        warn "Fix dotfiles/niri/config.kdl and re-run install.sh."
        exit 1
    fi
    ok "niri config validates"
fi

ok "dotfiles linked"
