#!/usr/bin/env bash
# rice-profile — switch the desktop between the "full" and "light" visual
# profiles, live, with no logout. One toggle drives BOTH halves of the rice:
#
#   • niri      — regenerates ~/.config/niri/config.kdl by concatenating
#                 config.base.kdl + config.<profile>.kdl (shadows, window
#                 translucency, spring-vs-cheap animations). niri auto-reloads.
#   • Quickshell — writes ~/.config/rice/profile, which the Profile.qml singleton
#                 watches; the bars re-flow instantly (cava waveform off in light,
#                 system-monitor poll backed off to 5s, surfaces opaque).
#
# Usage:
#   rice-profile            # print current profile
#   rice-profile status     # same
#   rice-profile full       # switch to full
#   rice-profile light      # switch to light
#   rice-profile toggle     # flip to the other one  (bound to Mod+Shift+P)
#
# "light" is the 4GB-MacBook profile: purely cosmetic/perf, no feature removed.
set -Eeuo pipefail

CONFmsg() { printf '%s\n' "$*"; }
die() { printf 'rice-profile: %s\n' "$*" >&2; exit 1; }

CFG="${XDG_CONFIG_HOME:-$HOME/.config}"
STATE_DIR="$CFG/rice"
STATE_FILE="$STATE_DIR/profile"
NIRI_DIR="$CFG/niri"
BASE="$NIRI_DIR/config.base.kdl"

current() {
    [[ -r "$STATE_FILE" ]] && [[ "$(tr -d '[:space:]' < "$STATE_FILE")" == "light" ]] \
        && echo light || echo full
}

# Regenerate ~/.config/niri/config.kdl from base + the chosen fragment. niri
# watches the file and reloads on its own; if a session is live we also poke it
# so the switch is instant even if the inotify watch is slow.
apply_niri() {
    local profile="$1"
    local frag="$NIRI_DIR/config.$profile.kdl"
    [[ -r "$BASE" ]] || die "missing $BASE (run install.sh / 08-link-dotfiles.sh)"
    [[ -r "$frag" ]] || die "missing $frag"

    local out="$NIRI_DIR/config.kdl"
    local tmp; tmp="$(mktemp "$NIRI_DIR/.config.kdl.XXXXXX")"
    {
        printf '// GENERATED by rice-profile (%s). Edit config.base.kdl or\n' "$profile"
        printf '// config.%s.kdl instead, then re-run: rice-profile %s\n\n' "$profile" "$profile"
        cat "$BASE"
        printf '\n'
        cat "$frag"
    } > "$tmp"

    # Validate before swapping in, so a broken fragment can never strand the
    # session with an unparseable config (niri would bounce to the greeter).
    if command -v niri >/dev/null 2>&1; then
        if ! niri validate -c "$tmp" >/tmp/rice-profile-niri.log 2>&1; then
            rm -f "$tmp"
            sed 's/^/    /' /tmp/rice-profile-niri.log >&2
            die "generated niri config failed to validate — keeping current config"
        fi
    fi
    mv -f "$tmp" "$out"

    # Nudge a running niri to reload immediately (no-op if none / unsupported).
    command -v niri >/dev/null 2>&1 && niri msg action load-config-file >/dev/null 2>&1 || true
}

set_profile() {
    local profile="$1"
    [[ "$profile" == "full" || "$profile" == "light" ]] || die "unknown profile: $profile"
    mkdir -p "$STATE_DIR"
    apply_niri "$profile"
    # Write the Quickshell state file LAST: once niri's config is in place, this
    # is the trigger the bars watch, so they reflow against a consistent world.
    printf '%s\n' "$profile" > "$STATE_FILE"
    CONFmsg "rice profile → $profile"
}

cmd="${1:-status}"
case "$cmd" in
    status|"")  current ;;
    full|light) set_profile "$cmd" ;;
    toggle)     [[ "$(current)" == "light" ]] && set_profile full || set_profile light ;;
    -h|--help)  sed -n '2,20p' "$0" ;;
    *)          die "usage: rice-profile [status|full|light|toggle]" ;;
esac
