#!/usr/bin/env bash
# theme-limine.sh — sync the Limine boot menu colours to the active rice palette
# on an ALREADY-INSTALLED system. Omarchy-style flat menu (solid dark bg, themed
# branding + 16-colour terminal palette) with a soft accent margin-gradient frame.
#
#     sudo scripts/theme-limine.sh                 # derive from ~/.config/rice/colors
#     sudo scripts/theme-limine.sh c1 c2 c3 c4     # explicit #rrggbb palette
#     sudo LIMINE_BRANDING="driftOS" scripts/theme-limine.sh
#
# Why a separate, root, opt-in command (and NOT part of `rice-theme set`):
#   Live theme cycling (Mod+Shift+T) is user-level and passwordless. The boot
#   menu lives on the ESP and is Secure-Boot SIGNED, so changing it needs root +
#   re-signing. Coupling it to every cycle would inject a sudo prompt into the
#   theme switcher. Run this when you want the boot menu to match your palette.
#
# Safety: this only writes /etc/limine-theme.conf (data) and makes the live
# generator call limine-emit-theme. The colours live INSIDE limine.conf, so they
# ride the existing failure-safe pipeline: limine-resign regenerates the config,
# re-enrolls its BLAKE2B checksum, re-signs primary+rescue on temp paths, and
# only swaps them in atomically once every step succeeds. A bad value can at
# worst make `niri validate`-style generation fail before any swap — never strand
# a half-updated pair. hash_mismatch_panic stays forced-on (Secure Boot); the
# unenrolled rescue entry remains your no-USB escape hatch.
#
# Idempotent and re-runnable. Counterpart to scripts/add-windows-limine.sh.
set -Eeuo pipefail

[[ $EUID -eq 0 ]] || { echo "run with sudo: sudo $0 $*" >&2; exit 1; }
[[ -x /usr/local/bin/limine-resign ]] || {
    echo "ERROR: /usr/local/bin/limine-resign missing — is this the Limine+sbctl install?" >&2
    exit 1
}
gen=/usr/local/bin/limine-regen-conf
[[ -f "$gen" ]] || { echo "ERROR: $gen missing" >&2; exit 1; }

# ---- 1) resolve the 4 palette colours -------------------------------------
# Priority: explicit args > the invoking user's rice palette > indigo default.
if [[ $# -eq 4 ]]; then
    C1="$1" C2="$2" C3="$3" C4="$4"
else
    USER_HOME="$(getent passwd "${SUDO_USER:-root}" | cut -d: -f6)"
    COLORS="$USER_HOME/.config/rice/colors"
    if [[ -r "$COLORS" ]]; then
        mapfile -t _c < <(grep -oE '#[0-9a-fA-F]{6}' "$COLORS")
        C1="${_c[0]:-#5b6ee0}" C2="${_c[1]:-#60a5fa}" C3="${_c[2]:-#22d3ee}" C4="${_c[3]:-#2dd4bf}"
        echo ">> palette from $COLORS"
    else
        C1="#5b6ee0" C2="#60a5fa" C3="#22d3ee" C4="#2dd4bf"
        echo ">> no rice palette found — using indigo default"
    fi
fi
[[ "$C1$C2$C3$C4" =~ ^(#[0-9a-fA-F]{6}){4}$ ]] || { echo "ERROR: need 4 #rrggbb colours (got: $C1 $C2 $C3 $C4)" >&2; exit 1; }

BRANDING="${LIMINE_BRANDING:-Arch Linux}"

# ---- 2) derive shades + write /etc/limine-theme.conf ----------------------
# Same lighter/darker model as rice-theme so the boot menu tracks the palette.
C1="$C1" C2="$C2" C3="$C3" C4="$C4" BRANDING="$BRANDING" python3 - <<'PY'
import os, colorsys
def hx(h): h=h.lstrip('#'); return tuple(int(h[i:i+2],16) for i in (0,2,4))
def hex6(r): return '%02x%02x%02x' % tuple(max(0,min(255,round(x))) for x in r)
def hsv(h): r,g,b=[x/255 for x in hx(h)]; return colorsys.rgb_to_hsv(r,g,b)
def back(hue,s,v):
    r,g,b=colorsys.hsv_to_rgb(hue,max(0,min(1,s)),max(0,min(1,v))); return hex6((r*255,g*255,b*255))
def lighter(h,f):
    hue,s,v=hsv(h); nv=v*f
    if nv>1: s=s/nv; nv=1.0
    return back(hue,s,nv)
def darker(h,f):
    hue,s,v=hsv(h); return back(hue,s,v/f)

c1,c2,c3,c4 = (os.environ[k] for k in ('C1','C2','C3','C4'))
# bg: very dark, slightly accent-tinted (keeps the indigo cast Omarchy gets from
# Tokyo Night's 1a1b26). Derived from the accent so it shifts with the palette.
bg        = darker(c1, 6.5)
bg_bright = darker(c1, 3.2)
black     = darker(c1, 2.4)          # palette[0]
black_br  = lighter(black, 1.35)
acc_br    = lighter(c1, 1.30)
fg        = "c9c9d0"                  # rice fg1
fg_bright = "f4f4f6"                  # rice fg0
help_c    = "8e8e96"                  # rice fg2
RED, RED_BR   = "f43f5e", "ff6b81"    # semantic — NOT themed (CLAUDE.md §13)
YEL, YEL_BR   = "e0af68", "f0c07a"    # amber — kept warm for legibility
# palette order: black;red;green;yellow;blue;magenta;cyan;white
pal  = ";".join([black, RED, c4.lstrip('#'), YEL, c2.lstrip('#'), c1.lstrip('#'), c3.lstrip('#'), fg])
palb = ";".join([black_br, RED_BR, lighter(c4,1.30), YEL_BR, lighter(c2,1.30), acc_br, lighter(c3,1.30), fg_bright])

conf = f"""# /etc/limine-theme.conf — colours + branding for the Limine boot menu.
# GENERATED by scripts/theme-limine.sh from the rice palette. Re-run to resync.
# Sourced by /usr/local/bin/limine-emit-theme. Bare RRGGBB hex (NO leading '#').
# The line below records the rice palette this menu was built from so rice-theme
# can detect drift and remind you to resync. (A comment — ignored when sourced.)
# rice-synced-colors: {c1} {c2} {c3} {c4}
LIMINE_BRANDING="{os.environ['BRANDING']}"
LIMINE_BRANDING_COLOUR="{acc_br}"
LIMINE_HELP_COLOUR="{help_c}"
LIMINE_HELP_COLOUR_BRIGHT="{fg}"
LIMINE_BACKDROP="{bg}"
LIMINE_TERM_BG="{bg}"
LIMINE_TERM_BG_BRIGHT="{bg_bright}"
LIMINE_TERM_FG="{fg}"
LIMINE_TERM_FG_BRIGHT="{fg_bright}"
LIMINE_PALETTE="{pal}"
LIMINE_PALETTE_BRIGHT="{palb}"
LIMINE_TERM_MARGIN="48"
LIMINE_TERM_MARGIN_GRADIENT="4"
"""
import tempfile, os as _os
dst = "/etc/limine-theme.conf"
# temp file must live on the SAME filesystem as the destination, or os.replace
# raises EXDEV (Invalid cross-device link) — /tmp is tmpfs, /etc is the root fs.
fd, tmp = tempfile.mkstemp(dir=_os.path.dirname(dst)); _os.write(fd, conf.encode()); _os.close(fd)
_os.replace(tmp, dst); _os.chmod(dst, 0o644)
print(">> wrote " + dst)
PY

# ---- 3) install the emitter (keep byte-identical to modules/06) ------------
install -Dm755 /dev/stdin /usr/local/bin/limine-emit-theme <<'EOF'
#!/usr/bin/env bash
set -Eeuo pipefail
# All colours are bare RRGGBB hex (NO leading '#'). Empty => Limine default.
LIMINE_BRANDING="Arch Linux"
LIMINE_BRANDING_COLOUR=""
LIMINE_HELP_COLOUR=""
LIMINE_HELP_COLOUR_BRIGHT=""
LIMINE_BACKDROP=""
LIMINE_TERM_BG=""
LIMINE_TERM_BG_BRIGHT=""
LIMINE_TERM_FG=""
LIMINE_TERM_FG_BRIGHT=""
LIMINE_PALETTE=""
LIMINE_PALETTE_BRIGHT=""
LIMINE_TERM_MARGIN=""
LIMINE_TERM_MARGIN_GRADIENT=""
[[ -f /etc/limine-theme.conf ]] && . /etc/limine-theme.conf
emit() { [[ -n "$2" ]] && echo "$1: $2"; return 0; }
echo "interface_branding: $LIMINE_BRANDING"
emit interface_branding_colour   "$LIMINE_BRANDING_COLOUR"
emit interface_help_colour        "$LIMINE_HELP_COLOUR"
emit interface_help_colour_bright "$LIMINE_HELP_COLOUR_BRIGHT"
emit backdrop                     "$LIMINE_BACKDROP"
emit term_background              "$LIMINE_TERM_BG"
emit term_background_bright       "$LIMINE_TERM_BG_BRIGHT"
emit term_foreground              "$LIMINE_TERM_FG"
emit term_foreground_bright       "$LIMINE_TERM_FG_BRIGHT"
emit term_palette                 "$LIMINE_PALETTE"
emit term_palette_bright          "$LIMINE_PALETTE_BRIGHT"
emit term_margin                  "$LIMINE_TERM_MARGIN"
emit term_margin_gradient         "$LIMINE_TERM_MARGIN_GRADIENT"
EOF
echo ">> installed /usr/local/bin/limine-emit-theme"

# ---- 4) make the live generator call the emitter (idempotent) -------------
# Replace the single static `echo "interface_branding: Arch Linux"` line with a
# call to limine-emit-theme. Mirrors the awk-patch approach in add-windows-limine.sh.
if grep -q 'limine-emit-theme' "$gen"; then
    echo ">> $gen already theme-aware — leaving as is"
else
    tmp="$(mktemp)"
    awk '
        /^[[:space:]]*echo "interface_branding: Arch Linux"$/ && !done {
            print "    limine-emit-theme        # branding + colours from /etc/limine-theme.conf"
            done=1; next
        }
        { print }
    ' "$gen" > "$tmp"
    grep -q 'limine-emit-theme' "$tmp" || { echo "ERROR: failed to patch $gen (branding line not found)" >&2; rm -f "$tmp"; exit 1; }
    install -Dm755 "$tmp" "$gen"
    rm -f "$tmp"
    echo ">> patched $gen"
fi

# ---- 5) regenerate config + re-enroll checksum + re-sign (atomic) ---------
/usr/local/bin/limine-resign
echo ">> limine-resign complete"

echo
echo "==== /boot/limine.conf (general section) ===="
sed -n '1,18p' /boot/limine.conf
